### ISSUE TITLE
Constructors missing new parameters

### ISSUE THREAD

**Issue by Cloppershy** [luckydonald/pytgbot#11]
The constructor for the Chat class seems to be missing the slow_mode_delay parameter, even though the from_array method parses that parameter. Thus, every time a Chat object is parsed (which is every time a message is sent), it fails.
(EDIT: This is affects other new fields, like can_join_groups, can_read_all_group_messages and supports_inline_queries for the User class)
EDIT EDIT: I didn't notice at first, but I caught you in the middle of an update. Looks like the error is with https://github.com/luckydonald/pytgbot/commit/dd4f5dafea0ae665d7d019f99bc00fb5c4080cd3, where somehow only part of the changes within the files are copied into the main directory. The files in code_generation/output are complete and have the updated constructors.

This code:
```python
bot = Bot(API_KEY)
bot.send_message(CHAT_ID, "Test")
```
causes this exception:
```python
DEBUG:pytgbot.bot:{'result': {'date': 1579924626, 'text': 'Test', 'from': {'username': 'trixiebooru_bot', 'first_name': 'Derpibooru Bot', 'id': 547893997, 'is_bot': True}, 'message_id': 963822, 'chat': {'username': 'Cloppershy', 'first_name': 'Clopper', 'id': 429870814, 'last_name': 'Shy 🇩🇪', 'type': 'private'}}, 'ok': True}
DEBUG:pytgbot.bot:Trying to parse {'date': 1579924626, 'from': {'username': 'trixiebooru_bot', 'first_name': 'Derpibooru Bot', 'id': 547893997, 'is_bot': True}, 'chat': {'username': 'Cloppershy', 'first_name': 'Clopper', 'id': 429870814, 'last_name': 'Shy 🇩🇪', 'type': 'private'}, 'message_id': 963822, 'text': 'Test'}
Traceback (most recent call last):
  File "D:/.../test.py", line 13, in <module>
    bot.send_message(WARNINGS_CHAT_ID, "Test")
  File "D:\...\pytgbot\bot.py", line 394, in send_message
    return Message.from_array(result)
  File "D:\...\pytgbot\api_types\receivable\updates.py", line 1127, in from_array
    data = Message.validate_array(array)
  File "D:\...\pytgbot\api_types\receivable\updates.py", line 1067, in validate_array
    data['chat'] = Chat.from_array(array.get('chat'))
  File "D:\...\pytgbot\api_types\receivable\peer.py", line 437, in from_array
    return Chat(**data)
TypeError: __init__() got an unexpected keyword argument 'slow_mode_delay'
```

**Comment by luckydonald** [comment]
Noticed that when updating to Bot API 4.6 as well.
Should be working now.

Thanks for your feedback!

**Comment by Cloppershy** [comment]
This was not fully fixed, the `Update` constructor is still missing the `poll_answer` parameter.

**Comment by luckydonald** [comment]
Dayum. I'll have a look.

**Comment by luckydonald** [comment]
Included in `v4.6.1`.
